// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0--rc2
// source: dnsQuery.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// this is a comment
type DnsQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip       string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Master   bool     `protobuf:"varint,2,opt,name=master,proto3" json:"master,omitempty"`
	Tport    string   `protobuf:"bytes,3,opt,name=tport,proto3" json:"tport,omitempty"`
	Domain   string   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Dnstype  uint32   `protobuf:"varint,5,opt,name=dnstype,proto3" json:"dnstype,omitempty"`
	Dnsclass uint32   `protobuf:"varint,6,opt,name=dnsclass,proto3" json:"dnsclass,omitempty"`
	Tdns     string   `protobuf:"bytes,7,opt,name=tdns,proto3" json:"tdns,omitempty"`
	Rr       []string `protobuf:"bytes,8,rep,name=rr,proto3" json:"rr,omitempty"`
}

func (x *DnsQuery) Reset() {
	*x = DnsQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnsQuery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsQuery) ProtoMessage() {}

func (x *DnsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_dnsQuery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsQuery.ProtoReflect.Descriptor instead.
func (*DnsQuery) Descriptor() ([]byte, []int) {
	return file_dnsQuery_proto_rawDescGZIP(), []int{0}
}

func (x *DnsQuery) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DnsQuery) GetMaster() bool {
	if x != nil {
		return x.Master
	}
	return false
}

func (x *DnsQuery) GetTport() string {
	if x != nil {
		return x.Tport
	}
	return ""
}

func (x *DnsQuery) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DnsQuery) GetDnstype() uint32 {
	if x != nil {
		return x.Dnstype
	}
	return 0
}

func (x *DnsQuery) GetDnsclass() uint32 {
	if x != nil {
		return x.Dnsclass
	}
	return 0
}

func (x *DnsQuery) GetTdns() string {
	if x != nil {
		return x.Tdns
	}
	return ""
}

func (x *DnsQuery) GetRr() []string {
	if x != nil {
		return x.Rr
	}
	return nil
}

var File_dnsQuery_proto protoreflect.FileDescriptor

var file_dnsQuery_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x6e, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xba, 0x01, 0x0a, 0x08, 0x44, 0x6e, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6e, 0x73, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x6e, 0x73, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x6e, 0x73, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x64, 0x6e, 0x73, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x64, 0x6e,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x64, 0x6e, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x72, 0x72, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x72, 0x72, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dnsQuery_proto_rawDescOnce sync.Once
	file_dnsQuery_proto_rawDescData = file_dnsQuery_proto_rawDesc
)

func file_dnsQuery_proto_rawDescGZIP() []byte {
	file_dnsQuery_proto_rawDescOnce.Do(func() {
		file_dnsQuery_proto_rawDescData = protoimpl.X.CompressGZIP(file_dnsQuery_proto_rawDescData)
	})
	return file_dnsQuery_proto_rawDescData
}

var file_dnsQuery_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dnsQuery_proto_goTypes = []interface{}{
	(*DnsQuery)(nil), // 0: DnsQuery
}
var file_dnsQuery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dnsQuery_proto_init() }
func file_dnsQuery_proto_init() {
	if File_dnsQuery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dnsQuery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnsQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dnsQuery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dnsQuery_proto_goTypes,
		DependencyIndexes: file_dnsQuery_proto_depIdxs,
		MessageInfos:      file_dnsQuery_proto_msgTypes,
	}.Build()
	File_dnsQuery_proto = out.File
	file_dnsQuery_proto_rawDesc = nil
	file_dnsQuery_proto_goTypes = nil
	file_dnsQuery_proto_depIdxs = nil
}
